/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as PublicRouteImport } from "./app/_public"
import { Route as PrivateRouteImport } from "./app/_private"
import { Route as PublicIndexRouteImport } from "./app/_public.index"
import { Route as PublicRegisterRouteImport } from "./app/_public.register"
import { Route as PublicLoginRouteImport } from "./app/_public.login"
import { Route as PrivateDocumentsRouteImport } from "./app/_private.documents"

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any)
const PrivateDocumentsRoute = PrivateDocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof PublicIndexRoute
  "/documents": typeof PrivateDocumentsRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
}
export interface FileRoutesByTo {
  "/": typeof PublicIndexRoute
  "/documents": typeof PrivateDocumentsRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_private": typeof PrivateRouteWithChildren
  "/_public": typeof PublicRouteWithChildren
  "/_private/documents": typeof PrivateDocumentsRoute
  "/_public/login": typeof PublicLoginRoute
  "/_public/register": typeof PublicRegisterRoute
  "/_public/": typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/documents" | "/login" | "/register"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/documents" | "/login" | "/register"
  id:
    | "__root__"
    | "/_private"
    | "/_public"
    | "/_private/documents"
    | "/_public/login"
    | "/_public/register"
    | "/_public/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private": {
      id: "/_private"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_public/": {
      id: "/_public/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/register": {
      id: "/_public/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_private/documents": {
      id: "/_private/documents"
      path: "/documents"
      fullPath: "/documents"
      preLoaderRoute: typeof PrivateDocumentsRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateDocumentsRoute: typeof PrivateDocumentsRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDocumentsRoute: PrivateDocumentsRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
