services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8080:8080"
  
  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server